/**
 * Staging — backend Stage table → CSV, 20-question battery.
 *
 * Companion to staging-backend-stage-table.cy.js (single-question version).
 * Runs the **same 20 questions** that produced backend-stage-MERGED-2026-05-22T14-32-07.csv
 * in one Cypress invocation. Output is a single CSV with one block per question,
 * shape-compatible with the May 22 merged file so the same merge / math scripts can read it.
 *
 * Run it with:
 *   CYPRESS_BASE_URL=https://staging.entwickler.de \
 *   CYPRESS_LOGIN_URL=https://staging.entwickler.de/login/ \
 *   CYPRESS_APP_ORIGIN=https://staging.entwickler.de \
 *   npx cypress run --browser chrome --spec 'cypress/e2e/staging-backend-stage-table-20q.cy.js'
 *
 * To run a subset for debugging, set CYPRESS_BATTERY_LIMIT to N (runs only first N questions).
 *
 * Generated by Claude — review before running.
 */

const STAGING_ORIGIN = 'https://staging.entwickler.de'

// =============================================================================
// The 20 questions from backend-stage-MERGED-2026-05-22T14-32-07.csv, in order.
// Q01..Q20 match the handoff matrix keys exactly.
// =============================================================================
const RUN_CONFIG = {
  /** Label for the CSV (shows up in the User field of each block). */
  user: 'Short LLM Answer',

  /** The 20-question list. Add / remove / reorder freely. */
  questions: [
    'What is What is the difference between unit, integration, and end-to-end tests?',
    'Wie funktioniert das Routing in Angular?',
    'I would like to build a pac-man to run in the browser',
    'Was sind LLM Evaluations und warum sollte man sie einsetzen?',
    'If I care most about speed vs most about realistic user flows, how should I split effort across test types?',
    'When should I use the Angular TestBed vs Cypress component tests vs Cypress E2E for the same feature?',
    'Welche Architekturmuster eignen sich für Microservices und wie unterscheiden sie sich voneinander?',
    'Erkläre die Prinzipien von Clean Architecture und wie man sie in einer Java-Anwendung umsetzt.',
    'Wie funktioniert Dependency Injection in Angular und welche Patterns gibt es dabei?',
    'Erkläre das Spring Boot Ökosystem und seine wichtigsten Module ausführlich.',
    'Was sind die besten Praktiken für Test-Driven Development in Java-Projekten?',
    'Wie richtet man eine vollständige CI/CD-Pipeline mit GitHub Actions für ein Angular-Projekt ein?',
    'Erkläre alle wichtigen Design Patterns aus dem Gang-of-Four-Buch mit Beispielen in Java oder TypeScript.',
    'Was sind die Unterschiede zwischen Microservices, Monolith, Modulith und Event-Driven Architecture? Erkläre Vor- und Nachteile jeder Architektur mit konkreten Beispielen.',
    'Erkläre das gesamte Spring Framework Ökosystem: Spring Boot, Spring Security, Spring Data, Spring Cloud — wie arbeiten sie zusammen?',
    'Wie funktioniert die Java Virtual Machine intern — Garbage Collection, JIT-Compiler, Classloading und Speicherverwaltung ausführlich erklärt.',
    'Welche Sicherheitsmaßnahmen muss eine moderne Webanwendung implementieren? Erkläre OWASP Top 10 mit konkreten Gegenmaßnahmen in Java oder Angular',
    'Erkläre Reactive Programming mit RxJS in Angular: Observables, Subjects, Operators und Best Practices.',
    'What is an array?',
    'What is cypress?'
  ]
}
// =============================================================================

const {
  extractBackendStageTableFromDom,
  backendStageTableDomReady,
  extractLlmAnswerText
} = require('../support/staging-backend-stage-dom')
const {
  backendStageReportToCsv,
  slugForFilename
} = require('../support/staging-backend-stage-parsers')

const REPORT_DIR = 'cypress/reports'

/**
 * Optional: only run the first N questions (for smoke / debug).
 * Set in the shell as CYPRESS_BATTERY_LIMIT=3 — Cypress automatically maps
 * any CYPRESS_* shell var into Cypress.env() with the prefix stripped.
 */
const limitRaw = Cypress.env('BATTERY_LIMIT')
const batteryLimit = (() => {
  if (limitRaw == null || limitRaw === '') return RUN_CONFIG.questions.length
  const n = parseInt(String(limitRaw), 10)
  if (Number.isNaN(n) || n <= 0) return RUN_CONFIG.questions.length
  return Math.min(RUN_CONFIG.questions.length, n)
})()

const questionList = RUN_CONFIG.questions.slice(0, batteryLimit)

/** Wait for Stage table (slow accounts / long chat history may need longer). */
const TABLE_WAIT_MS = 120000

/** Set in `before()` — must live here so helpers outside `describe` can read it. */
let reportTimestamp = ''

function reportFilename() {
  return `backend-stage-20q-${slugForFilename(RUN_CONFIG.user)}-${reportTimestamp}.csv`
}

/**
 * Persist a CSV that matches the May 22 merged-file shape:
 * one block per question, each with its own User / Question header.
 *
 * `backendStageReportToCsv` from the existing parser writes ONE block per
 * call, so we concatenate per-question blocks here.
 */
function persistReportCsv(allRunsByQuestion) {
  if (!reportTimestamp) return cy.wrap(null, { log: false })
  if (!allRunsByQuestion.length) return cy.wrap(null, { log: false })

  const blocks = allRunsByQuestion.map((entry) =>
    backendStageReportToCsv({
      user: RUN_CONFIG.user,
      question: entry.question,
      runs: [{ rows: entry.rows, answerLength: entry.answerLength }]
    })
  )

  // Concatenate blocks with a blank line in between (matches May 22 merged shape).
  const data = blocks.join('\n\n') + '\n'
  const filename = reportFilename()
  return cy
    .task('writeReport', { data, filename })
    .then(() => `${REPORT_DIR}/${filename}`)
}

describe(
  'Staging — backend Stage table (20-question battery) → CSV',
  { testIsolation: false, timeout: 14400000 },
  () => {
    /** @type {Array<{question: string, rows: Array, answerLength: number}>} */
    const allRunsByQuestion = []

    before(() => {
      Cypress.config('baseUrl', STAGING_ORIGIN)
      Cypress.env('APP_ORIGIN', STAGING_ORIGIN)
      reportTimestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5)

      cy.authLogin()
      cy.userLogin()
      cy.url({ timeout: 15000 }).should('include', '/reader/intelligence')
      cy.waitForComposerTextareaReady({ timeout: 30000 })
    })

    afterEach(function () {
      if (allRunsByQuestion.length) {
        persistReportCsv(allRunsByQuestion)
      }
    })

    after(() => {
      cy.then(() =>
        persistReportCsv(allRunsByQuestion).then((csvPath) => {
          if (csvPath) {
            cy.log(
              `CSV: ${Cypress.config('projectRoot')}/${csvPath} | user=${RUN_CONFIG.user} | questions=${allRunsByQuestion.length}`
            )
          }
        })
      )
    })

    questionList.forEach((question, index) => {
      const labelShort = question.length > 60 ? question.slice(0, 57) + '…' : question
      it(`Q${String(index + 1).padStart(2, '0')}/${questionList.length} — ${labelShort}`, () => {
        // Between questions: full page reload (NOT the new-chat UI click).
        // The 2026-05-28 runs showed that the new-chat UI accumulates session
        // state — by Q09 the app wedged in "Formuliere Antwort…" and every
        // subsequent question's send button stayed disabled. Visiting
        // /reader/intelligence fresh isolates each question completely, the
        // same way the May 22 baseline did (each question = separate Cypress
        // invocation).
        if (index > 0) {
          cy.visitWithAuth(`${STAGING_ORIGIN}/reader/intelligence`)
          cy.url({ timeout: 15000 }).should('include', '/reader/intelligence')
          cy.waitForComposerTextareaReady({ timeout: 120000 })
        }

        cy.waitForComposerTextareaReady({ timeout: 180000 })
        cy.getChatInput().clear().type(question, { force: true })
        cy.waitForComposerSendEnabled()
        cy.getComposerSendButton().filter(':visible').first().click()
        cy.waitForComposerReadyForNewQuestion({ timeout: 600000 })

        cy.document({ timeout: TABLE_WAIT_MS }).should((doc) => {
          const check = backendStageTableDomReady(doc.body)
          if (!check.ready) {
            const stages = check.rows.map((r) => r.STAGE).join(' | ') || '(none)'
            throw new Error(
              `Q${index + 1}: Stage table not ready after ${TABLE_WAIT_MS}ms — rows=${check.rowCount}; found: ${stages}`
            )
          }
        })

        cy.document().then((doc) => {
          const rows = extractBackendStageTableFromDom(doc.body)
          expect(rows.length, `Q${index + 1}: row count`).to.be.greaterThan(0)
          const answerText = extractLlmAnswerText(doc.body)
          allRunsByQuestion.push({
            question,
            rows,
            answerLength: answerText.length
          })
          return persistReportCsv(allRunsByQuestion)
        })
      })
    })
  }
)
