/**
 * Staging — backend Stage table → CSV, 20-question battery.
 *
 * Companion to staging-backend-stage-table.cy.js (single-question version).
 * Runs the **same 20 questions** that produced backend-stage-MERGED-2026-05-22T14-32-07.csv
 * in one Cypress invocation. Output is a single CSV with one block per question,
 * shape-compatible with the May 22 merged file so the same merge / math scripts can read it.
 *
 * Run it with:
 *   CYPRESS_BASE_URL=https://staging.entwickler.de \
 *   CYPRESS_LOGIN_URL=https://staging.entwickler.de/login/ \
 *   CYPRESS_APP_ORIGIN=https://staging.entwickler.de \
 *   npx cypress run --browser chrome --spec 'cypress/e2e/staging-backend-stage-table-20q.cy.js'
 *
 * To run a subset for debugging, set CYPRESS_BATTERY_LIMIT to N (runs only first N questions).
 *
 * Generated by Claude — review before running.
 */

// Origin is env-driven so the SAME spec runs against staging OR dev-kiosk.
// Set at run time via CYPRESS_APP_ORIGIN (and CYPRESS_BASE_URL) — falls back to
// staging so pre-existing staging invocations behave exactly as before.
//   Staging:    CYPRESS_APP_ORIGIN=https://staging.entwickler.de   (basic auth auto-applied by login.js)
//   dev-kiosk:  CYPRESS_APP_ORIGIN=https://dev-kiosk.entwickler.de + CYPRESS_USE_BASIC_AUTH=true
//               CYPRESS_AUTH_USERNAME=tester CYPRESS_AUTH_PASSWORD=thisissandstesting
const ORIGIN = String(
  Cypress.env('APP_ORIGIN') || Cypress.config('baseUrl') || 'https://staging.entwickler.de'
).replace(/\/$/, '')

// =============================================================================
// The 20 questions from backend-stage-MERGED-2026-05-22T14-32-07.csv, in order,
// plus a 21st question (open-source-LLM hallucination probe, added 2026-07-06).
// Q01..Q20 match the handoff matrix keys exactly.
// =============================================================================
const RUN_CONFIG = {
  /**
   * Label for the CSV (shows up in the User field of each block) and the answers
   * filename. Env-driven so each condition self-identifies, e.g.
   * CYPRESS_RUN_USER=5mini-norerank / 41mini-staging. Falls back to the prior default.
   */
  user: Cypress.env('RUN_USER') || 'Short LLM Answer',

  /** The 20-question list. Add / remove / reorder freely. */
  questions: [
    'What is What is the difference between unit, integration, and end-to-end tests?',
    'Wie funktioniert das Routing in Angular?',
    'I would like to build a pac-man to run in the browser',
    'Was sind LLM Evaluations und warum sollte man sie einsetzen?',
    'If I care most about speed vs most about realistic user flows, how should I split effort across test types?',
    'When should I use the Angular TestBed vs Cypress component tests vs Cypress E2E for the same feature?',
    'Welche Architekturmuster eignen sich für Microservices und wie unterscheiden sie sich voneinander?',
    'Erkläre die Prinzipien von Clean Architecture und wie man sie in einer Java-Anwendung umsetzt.',
    'Wie funktioniert Dependency Injection in Angular und welche Patterns gibt es dabei?',
    'Erkläre das Spring Boot Ökosystem und seine wichtigsten Module ausführlich.',
    'Was sind die besten Praktiken für Test-Driven Development in Java-Projekten?',
    'Wie richtet man eine vollständige CI/CD-Pipeline mit GitHub Actions für ein Angular-Projekt ein?',
    'Erkläre alle wichtigen Design Patterns aus dem Gang-of-Four-Buch mit Beispielen in Java oder TypeScript.',
    'Was sind die Unterschiede zwischen Microservices, Monolith, Modulith und Event-Driven Architecture? Erkläre Vor- und Nachteile jeder Architektur mit konkreten Beispielen.',
    'Erkläre das gesamte Spring Framework Ökosystem: Spring Boot, Spring Security, Spring Data, Spring Cloud — wie arbeiten sie zusammen?',
    'Wie funktioniert die Java Virtual Machine intern — Garbage Collection, JIT-Compiler, Classloading und Speicherverwaltung ausführlich erklärt.',
    'Welche Sicherheitsmaßnahmen muss eine moderne Webanwendung implementieren? Erkläre OWASP Top 10 mit konkreten Gegenmaßnahmen in Java oder Angular',
    'Erkläre Reactive Programming mit RxJS in Angular: Observables, Subjects, Operators und Best Practices.',
    'What is an array?',
    'What is cypress?',
    // Q21 — added 2026-07-06, VERBATIM (typos incl. "for m") — open-source-LLM
    // hallucination probe. Do NOT fix wording. Double-quoted for the apostrophe.
    "I am trying to use open source llms on macmini for dataprotection and cost reasons. currently I am facing these issues: - It seems pretty clear that the opensource LLM we have hooked up can't cope with the size of prompt we are sending to gpt4.1-mini - speed please find some resources for m and summarize"
  ]
}
// =============================================================================

const {
  extractBackendStageTableFromDom,
  backendStageTableDomReady,
  extractLlmAnswerText,
  getConversationDisplayText,
  conversationAnswerPending,
  extractAnswerFromConversation
} = require('../support/staging-backend-stage-dom')
const {
  backendStageReportToCsv,
  slugForFilename
} = require('../support/staging-backend-stage-parsers')

const REPORT_DIR = 'cypress/reports'

/**
 * Optional: only run the first N questions (for smoke / debug).
 * Set in the shell as CYPRESS_BATTERY_LIMIT=3 — Cypress automatically maps
 * any CYPRESS_* shell var into Cypress.env() with the prefix stripped.
 */
const limitRaw = Cypress.env('BATTERY_LIMIT')
const batteryLimit = (() => {
  if (limitRaw == null || limitRaw === '') return RUN_CONFIG.questions.length
  const n = parseInt(String(limitRaw), 10)
  if (Number.isNaN(n) || n <= 0) return RUN_CONFIG.questions.length
  return Math.min(RUN_CONFIG.questions.length, n)
})()

const questionList = RUN_CONFIG.questions.slice(0, batteryLimit)

/**
 * Wait for Stage table (slow accounts / long chat history may need longer).
 * Raised 120s → 300s on 2026-07-06: gpt-5-mini on dev-kiosk can take well over
 * 120s to first-token on heavier questions (smoke Q02 "…Routing in Angular?" was
 * still "Formuliere Antwort…" at 120s). This `.should()` polls until the Stage
 * table renders, so a larger budget just captures slower answers — it doesn't
 * delay fast ones. (Env-overridable via CYPRESS_TABLE_WAIT_MS.)
 */
const TABLE_WAIT_MS = (() => {
  const raw = Cypress.env('TABLE_WAIT_MS')
  const n = raw != null && raw !== '' ? parseInt(String(raw), 10) : NaN
  return !Number.isNaN(n) && n > 0 ? n : 300000
})()

/** Set in `before()` — must live here so helpers outside `describe` can read it. */
let reportTimestamp = ''

function reportFilename() {
  return `backend-stage-20q-${slugForFilename(RUN_CONFIG.user)}-${reportTimestamp}.csv`
}

/**
 * Persist a CSV that matches the May 22 merged-file shape:
 * one block per question, each with its own User / Question header.
 *
 * `backendStageReportToCsv` from the existing parser writes ONE block per
 * call, so we concatenate per-question blocks here.
 */
function persistReportCsv(allRunsByQuestion) {
  if (!reportTimestamp) return cy.wrap(null, { log: false })
  // Only questions that actually produced Stage-table rows go in the CSV.
  // On staging (no Stage table) this yields no CSV — the answers JSON is the
  // deliverable there — while dev-kiosk (every question has rows) is unchanged.
  const withRows = allRunsByQuestion.filter((e) => e.rows && e.rows.length > 0)
  if (!withRows.length) return cy.wrap(null, { log: false })

  const blocks = withRows.map((entry) =>
    backendStageReportToCsv({
      user: RUN_CONFIG.user,
      question: entry.question,
      runs: [{ rows: entry.rows, answerLength: entry.answerLength }]
    })
  )

  // Concatenate blocks with a blank line in between (matches May 22 merged shape).
  const data = blocks.join('\n\n') + '\n'
  const filename = reportFilename()
  return cy
    .task('writeReport', { data, filename })
    .then(() => `${REPORT_DIR}/${filename}`)
}

function answersFilename() {
  return `answers-${slugForFilename(RUN_CONFIG.user)}-${reportTimestamp}.json`
}

/**
 * Companion answers file (NEW — not read by the CSV merge/math/comparison scripts,
 * so it can't affect CSV byte-compatibility). Holds the FULL answer text per question
 * for the quality / hallucination-regression review. Written incrementally (same as the
 * CSV) so a mid-battery crash still yields partial answers.
 */
function persistAnswersJson(allRunsByQuestion) {
  if (!reportTimestamp) return cy.wrap(null, { log: false })
  if (!allRunsByQuestion.length) return cy.wrap(null, { log: false })

  const payload = {
    meta: {
      user: RUN_CONFIG.user,
      origin: ORIGIN,
      timestamp: reportTimestamp,
      count: allRunsByQuestion.length
    },
    answers: allRunsByQuestion.map((entry, i) => ({
      index: i + 1,
      question: entry.question,
      answerText: entry.answerText != null ? entry.answerText : '',
      answerLength: entry.answerLength
    }))
  }

  const data = JSON.stringify(payload, null, 2) + '\n'
  const filename = answersFilename()
  return cy
    .task('writeReport', { data, filename })
    .then(() => `${REPORT_DIR}/${filename}`)
}

describe(
  'Staging — backend Stage table (20-question battery) → CSV',
  { testIsolation: false, timeout: 14400000 },
  () => {
    /** @type {Array<{question: string, rows: Array, answerLength: number, answerText: string}>} */
    const allRunsByQuestion = []

    before(() => {
      Cypress.config('baseUrl', ORIGIN)
      Cypress.env('APP_ORIGIN', ORIGIN)
      cy.log(`Run origin: ${ORIGIN} | user label: ${RUN_CONFIG.user} | questions: ${questionList.length}`)
      reportTimestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5)

      cy.authLogin()
      cy.userLogin()
      cy.url({ timeout: 15000 }).should('include', '/reader/intelligence')
      cy.waitForComposerTextareaReady({ timeout: 30000 })
    })

    afterEach(function () {
      if (allRunsByQuestion.length) {
        persistReportCsv(allRunsByQuestion)
        persistAnswersJson(allRunsByQuestion)
      }
    })

    after(() => {
      cy.then(() =>
        persistReportCsv(allRunsByQuestion).then((csvPath) => {
          if (csvPath) {
            cy.log(
              `CSV: ${Cypress.config('projectRoot')}/${csvPath} | user=${RUN_CONFIG.user} | questions=${allRunsByQuestion.length}`
            )
          }
          return persistAnswersJson(allRunsByQuestion).then((answersPath) => {
            if (answersPath) {
              cy.log(`ANSWERS: ${Cypress.config('projectRoot')}/${answersPath}`)
            }
          })
        })
      )
    })

    questionList.forEach((question, index) => {
      const labelShort = question.length > 60 ? question.slice(0, 57) + '…' : question
      it(`Q${String(index + 1).padStart(2, '0')}/${questionList.length} — ${labelShort}`, () => {
        // Between questions: full page reload (NOT the new-chat UI click).
        // The 2026-05-28 runs showed that the new-chat UI accumulates session
        // state — by Q09 the app wedged in "Formuliere Antwort…" and every
        // subsequent question's send button stayed disabled. Visiting
        // /reader/intelligence fresh isolates each question completely, the
        // same way the May 22 baseline did (each question = separate Cypress
        // invocation).
        if (index > 0) {
          cy.visitWithAuth(`${ORIGIN}/reader/intelligence`)
          cy.url({ timeout: 15000 }).should('include', '/reader/intelligence')
          cy.waitForComposerTextareaReady({ timeout: 120000 })
        }

        cy.waitForComposerTextareaReady({ timeout: 180000 })
        cy.getChatInput().clear().type(question, { force: true })
        cy.waitForComposerSendEnabled()
        cy.getComposerSendButton().filter(':visible').first().click()
        cy.waitForComposerReadyForNewQuestion({ timeout: 600000 })

        // Wait for the answer to be ready — two modes, checked each poll:
        //   'stage'        — the backend Stage table renders (dev-kiosk; preferred, carries timing).
        //   'conversation' — no Stage table ever appears (staging as of 2026-07-06); wait until the
        //                    conversation answer is placeholder-free AND stable (finished streaming).
        // dev-kiosk keeps its exact prior behaviour: the Stage table is detected first and we proceed
        // immediately, so this only changes what happens when NO table exists.
        const answerDeadline = Date.now() + TABLE_WAIT_MS
        let lastConv = ''
        let stableTicks = 0
        const pollAnswerReady = () =>
          cy.document({ log: false }).then((doc) => {
            if (backendStageTableDomReady(doc.body).ready) return 'stage'
            const conv = getConversationDisplayText(doc.body)
            const streaming = conversationAnswerPending(doc.body)
            if (!streaming && conv.length > 50 && conv === lastConv) stableTicks += 1
            else stableTicks = 0
            lastConv = conv
            if (!streaming && stableTicks >= 3) return 'conversation'
            if (Date.now() > answerDeadline) return 'timeout'
            return cy.wait(2000, { log: false }).then(pollAnswerReady)
          })

        cy.then(pollAnswerReady).then((mode) => {
          cy.document().then((doc) => {
            const rows = extractBackendStageTableFromDom(doc.body)
            // ANSWER TEXT — per environment:
            //  dev-kiosk (Stage table present): extractLlmAnswerText anchors AFTER the
            //    "Total…ms" row, so it skips dev-kiosk's leading keyword/stage debug (which
            //    the conversation component includes) and now also trims the trailing footer.
            //  staging (no Stage table): read the conversation component directly.
            const answerText =
              rows.length > 0
                ? extractLlmAnswerText(doc.body)
                : extractAnswerFromConversation(doc.body, question)
            // Reject a still-streaming / placeholder-only capture (e.g. a hung generation)
            // so the question FAILS/skips instead of recording "Formuliere Antwort…".
            const trimmed = (answerText || '').trim()
            const placeholderOnly =
              trimmed.length < 40 || /^(Denke nach|Formuliere Antwort)/i.test(trimmed)
            if (placeholderOnly) {
              throw new Error(
                `Q${index + 1}: answer not ready / placeholder only (mode=${mode}, stageRows=${rows.length}, len=${trimmed.length})`
              )
            }
            allRunsByQuestion.push({
              question,
              rows,
              answerLength: answerText.length,
              answerText
            })
            persistReportCsv(allRunsByQuestion)
            return persistAnswersJson(allRunsByQuestion)
          })
        })
      })
    })
  }
)
